# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='foto/products/'),
        ),
    ]
