# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 20:06
from __future__ import unicode_literals

import biprod.apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=biprod.apps.products.models.content_file_products),
        ),
    ]
